version: 0.0
os: linux
files:
  - source: react/build/
    destination: /usr/share/nginx/html/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/configure_nginx
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root