version: 0.0
os: linux
files:
  - source: handyman/
    destination: /home/ubuntu/handyman/
hooks:
  BeforeInstall:
    - location: scripts/install
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start
      timeout: 300
      runas: root