version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  
  pre_build:
    commands:
      - echo "Starting pre-build phase"
  
  build:
    commands:
      - echo "Build phase completed"

artifacts:
  files:
    - backend/**/*
    - appspec.yml
    - scripts/**/*
  base-directory: .
  discard-paths: no
