version: 0.2

env:
  variables:
    REACT_APP_API_URL: "/api"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing custom Node.js version 16 ..."
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd react
      - codebuild-breakpoint
      - npm ci
  build:
    commands:
      - echo Building React application...
      - npm run build
  post_build:
    commands:
      - echo Packaging build...
      - aws s3 sync --acl public-read build/ s3://123456-abdullah-bucket/
      - cd ..
      - zip -r build.zip react/build
      - codebuild-breakpoint

cache:
  paths:
    - 'react/node_modules/**/*'
  files:
    - react/package.json
    - react/package-lock.json

secondary-cache:
  paths:
    - 'react/build/**/*'
  files:
    - react/src/**/*

artifacts:
  files:
    - build.zip
  discard-paths: no
