version: 0.0
os: linux
files:
  - source: backend/backend/
    destination: /home/ec2-user/news-app-backend/
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root