#!/bin/bash -ex

# venv is a Python virtual environment
python3 -m venv /home/ec2-user/news-app-backend/.venv

# Activate the virtual environment
source /home/ec2-user/news-app-backend/.venv/bin/activate

# Install Python dependencies
cd /home/ec2-user/news-app-backend && pip install -r requirements.txt

deactivate