#!/bin/bash -ex

# venv is a Python virtual environment
cd /home/ec2-user/news-app-backend
python3 -m venv .venv

# Activate the virtual environment
source .venv/bin/activate

# Install Python dependencies
pip3 install -r requirements.txt
if [ ! -f .env ]; then 
echo 'MONGO_URI=mongodb://localhost:27017/' >> .env; 
fi

deactivate