#!/bin/bash -ex
# Update system packages
yum update -y


curl -fsSL https://rpm.nodesource.com/setup_18.x | sudo bash -
yum install -y nodejs

# Install the pm2 package
which pm2 || npm install -g pm2

if [ ! -d /home/ec2-user/news-app-backend/ ]; then
    mkdir -p /home/ec2-user/news-app-backend/
fi

if [ -d /usr/share/nginx/html/ ]; then
    rm -rf /home/ec2-user/news-app-backend/*
fi