services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root_user
      MONGO_INITDB_ROOT_PASSWORD: example
    command:
      - "mongod"
      - "--replSet=rs0"
      - "--bind_ip_all"
    networks:
      - mongo-network
    volumes:
      - mongo-db-data:/data/db/

volumes:
  mongo-db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/mnt/mongodb'
networks:
  mongo-network:
    name: mongo-network